1. Create a 2-by-3 array with ones, a 3-by-3 array with zeros and a 2-by-5 array with sevens.

In [1]:
import numpy as np
a=np.ones((2,3))
b=np.zeros((3,3))
c=np.full((2,5),7)
print(a)
print(b)
print(c)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[7 7 7 7 7]
 [7 7 7 7 7]]


2. Use arange to create a 2-by-2 array containing the numbers 0–3. Use broadcasting to perform each operation.

In [2]:
import numpy as np
a=np.arange(4).reshape(2,2)
print(a**3)
print(a+7)
print(a*2)

[[ 0  1]
 [ 8 27]]
[[ 7  8]
 [ 9 10]]
[[0 2]
 [4 6]]


3. Create arrays and multiply.

In [3]:
import numpy as np
a=np.arange(2,20,2).reshape(3,3)
b=np.arange(9,0,-1).reshape(3,3)
print(a*b)

[[18 32 42]
 [48 50 48]
 [42 32 18]]


4. Swap first two rows and columns.

In [4]:
import numpy as np
a=np.arange(1,10).reshape(3,3)
a[[0,1]]=a[[1,0]]
a[:,[0,1]]=a[:,[1,0]]
print(a)

[[5 4 6]
 [2 1 3]
 [8 7 9]]


5. Create a 2-by-5 array from given lists.

In [5]:
import numpy as np
a=np.array([[2,3,5,7,11],[13,17,19,23,29]])
print(a)

[[ 2  3  5  7 11]
 [13 17 19 23 29]]


6. Powers of 2 flatten and ravel.

In [6]:
import numpy as np
a=2**np.arange(6).reshape(2,3)
print(a.flatten())
print(a.ravel())
print(a)

[ 1  2  4  8 16 32]
[ 1  2  4  8 16 32]
[[ 1  2  4]
 [ 8 16 32]]


7. Most frequent values.

In [7]:
import numpy as np
a=np.array([6,9,5,1,7,5,1,0,1,5,5,0,8,9,0,7,0,7,6,5,1,1,9,5,3,8,7,9,6,3,4,5,9,7,2,7,0,2,2,6])
u,c=np.unique(a,return_counts=True)
print(u[c==c.max()])

[5]


8. Linspace reshape convert to int.

In [8]:
import numpy as np
a=np.linspace(1.1,6.6,6).reshape(2,3)
print(a.astype(int))

[[1 2 3]
 [4 5 6]]


9. format_2d_array function.

In [9]:
def format_2d_array(arr):
    w=max(len(str(x)) for r in arr for x in r)
    return '\n'.join(' '.join(f"{x:>{w}}" for x in r) for r in arr)
print(format_2d_array([[1,22],[333,4]]))

  1  22
333   4


10. Array slicing tasks.

In [10]:
import numpy as np
a=np.arange(1,16).reshape(3,5)
print(a[2])
print(a[:,4])
print(a[0:2])
print(a[:,2:5])
print(a[1,4])
print(a[[1,2]][:, [0,2,4]])

[11 12 13 14 15]
[ 5 10 15]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]
10
[[ 6  8 10]
 [11 13 15]]


11. Stacking tasks.

In [11]:
import numpy as np
a1=np.array([[0,1],[2,3]])
a2=np.array([[4,5],[6,7]])
print(np.vstack((a1,a2)))
print(np.hstack((a1,a2)))
a4=np.hstack((a1,a2))
print(np.vstack((a4,a4)))
a3=np.vstack((a1,a2))
print(np.hstack((a3,a3)))

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1 4 5]
 [2 3 6 7]]
[[0 1 4 5]
 [2 3 6 7]
 [0 1 4 5]
 [2 3 6 7]]
[[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]
 [6 7 6 7]]


12. Concatenate implementation.

In [12]:
import numpy as np
a1=np.array([[0,1],[2,3]])
a2=np.array([[4,5],[6,7]])
print(np.concatenate((a1,a2),axis=0))

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


13. Tile checkerboard.

In [13]:
import numpy as np
print(np.tile(['-','*'],(4,4)))

[['-' '*' '-' '*' '-' '*' '-' '*']
 ['-' '*' '-' '*' '-' '*' '-' '*']
 ['-' '*' '-' '*' '-' '*' '-' '*']
 ['-' '*' '-' '*' '-' '*' '-' '*']]


14. Bincount random array.

In [14]:
import numpy as np
a=np.random.randint(0,100,(5,5))
print(np.bincount(a.flatten()))

[0 0 0 0 1 0 0 0 0 2 1 1 0 0 1 0 0 2 0 0 0 0 1 1 0 1 0 2 0 0 0 0 0 0 1 0 0
 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 1 0 0 0 0 0 0 2 0 0 0 1]


15. median and mode functions.

In [15]:
import numpy as np
def median(a):return np.median(a)
def mode(a):u,c=np.unique(a,return_counts=True);return u[c.argmax()]
print(median([1,2,3]))
print(mode([1,1,2,3]))

2.0
1


16. Extract 5x5x2.

In [16]:
import numpy as np
a=np.random.rand(9,9,2)
print(a[0:5,0:5])

[[[0.89437698 0.79620864]
  [0.07094235 0.19182444]
  [0.35667547 0.47014912]
  [0.65703168 0.72368379]
  [0.48568326 0.84452202]]

 [[0.89918658 0.58412552]
  [0.00687584 0.54838915]
  [0.08153659 0.40334642]
  [0.42503389 0.36043009]
  [0.67095046 0.43630347]]

 [[0.99348431 0.76452315]
  [0.03434497 0.56123623]
  [0.43353873 0.88477523]
  [0.36839362 0.1821412 ]
  [0.33125621 0.31147816]]

 [[0.08077853 0.3137038 ]
  [0.55959192 0.19943167]
  [0.96965753 0.4785803 ]
  [0.43529799 0.85509536]
  [0.82835819 0.17078913]]

 [[0.44296598 0.14581701]
  [0.20681122 0.62800754]
  [0.28180434 0.23553307]
  [0.01281274 0.39454576]
  [0.64886223 0.20887501]]]


17. Sort each column.

In [17]:
import numpy as np
a=np.random.rand(4,4)
print(np.sort(a,axis=0))

[[0.31377711 0.44636064 0.07608737 0.48994496]
 [0.37173958 0.46305364 0.49600034 0.57130198]
 [0.45234974 0.60244282 0.52213376 0.96129311]
 [0.91076559 0.77603712 0.52546429 0.97559845]]


18. Convert DataFrame column to Series.

In [18]:
import pandas as pd
df=pd.DataFrame({'A':[1,2,3],'B':[4,5,6]})
print(df['A'])

0    1
1    2
2    3
Name: A, dtype: int64


19. Elements in s1 not in s2.

In [19]:
import pandas as pd
s1=pd.Series([1,2,3,4,2])
s2=pd.Series([3,4,5,6])
print(s1[~s1.isin(s2)])

0    1
1    2
4    2
dtype: int64


20. Index of smallest and largest.

In [20]:
import pandas as pd
s=pd.Series([1,1,3,7,88,12,88,23,3,1,9,0])
print(s.idxmin(),s.idxmax())

11 4


21. Series vowel filtering.

In [21]:
import pandas as pd
L=['Cry','Apple','Orange','Sky','Banana']
s=pd.Series(L)
v=s[s.str.contains('[AEIOUaeiou]')]
st=s[s.str.contains('^[AEIOUaeiou]')]
print(v)
print(st)

1     Apple
2    Orange
4    Banana
dtype: object
1     Apple
2    Orange
dtype: object


22. Series tasks.

In [22]:
import pandas as pd, numpy as np
print(pd.Series([7,11,13,17]))
print(pd.Series([100.0]*5))
print(pd.Series(np.random.randint(0,101,20)).describe())
t=pd.Series([98.6,98.9,100.2,97.9],index=['Julie','Charlie','Sam','Andrea'])
print(t)
print(pd.Series(t.to_dict()))

0     7
1    11
2    13
3    17
dtype: int64
0    100.0
1    100.0
2    100.0
3    100.0
4    100.0
dtype: float64
count    20.000000
mean     49.350000
std      27.787303
min       7.000000
25%      23.000000
50%      52.000000
75%      71.500000
max      98.000000
dtype: float64
Julie       98.6
Charlie     98.9
Sam        100.2
Andrea      97.9
dtype: float64
Julie       98.6
Charlie     98.9
Sam        100.2
Andrea      97.9
dtype: float64


23. DataFrame tasks.

In [23]:
import pandas as pd
df=pd.DataFrame({'Maxine':[1,2,3],'James':[4,5,6],'Amanda':[7,8,9]})
df2=pd.DataFrame({'Maxine':[1,2,3],'James':[4,5,6],'Amanda':[7,8,9]},index=['Morning','Afternoon','Evening'])
print(df2['Maxine'])
print(df2.loc['Morning'])
print(df2.loc[['Morning','Evening']])
print(df2[['Amanda','Maxine']])
print(df2.loc[['Morning','Afternoon'],['Amanda','Maxine']])
print(df2.describe())
print(df2.T)
print(df2.sort_index(axis=1))

Morning      1
Afternoon    2
Evening      3
Name: Maxine, dtype: int64
Maxine    1
James     4
Amanda    7
Name: Morning, dtype: int64
         Maxine  James  Amanda
Morning       1      4       7
Evening       3      6       9
           Amanda  Maxine
Morning         7       1
Afternoon       8       2
Evening         9       3
           Amanda  Maxine
Morning         7       1
Afternoon       8       2
       Maxine  James  Amanda
count     3.0    3.0     3.0
mean      2.0    5.0     8.0
std       1.0    1.0     1.0
min       1.0    4.0     7.0
25%       1.5    4.5     7.5
50%       2.0    5.0     8.0
75%       2.5    5.5     8.5
max       3.0    6.0     9.0
        Morning  Afternoon  Evening
Maxine        1          2        3
James         4          5        6
Amanda        7          8        9
           Amanda  James  Maxine
Morning         7      4       1
Afternoon       8      5       2
Evening         9      6       3
